let data = {
	"pancakes":[{"id":1,"name":"Go Bacon","img":"./photos/bacon-pancakes-resize-6.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1 tablespoon sugar", "1/2 teaspoon salt", "2 tablespoons unsalted butter, melted", "Additional butter or oil for cooking"],
		"instructions":["Cook the bacon in a skillet over medium heat until crispy. Transfer to a paper towel-lined plate and crumble into small pieces.",
		"In a large bowl, whisk together the flour, sugar, baking powder, and salt.",
		"In a separate bowl, whisk the egg, milk, and melted butter.",
		"Add the wet ingredients to the dry ingredients and whisk until just combined. Stir in the crumbled bacon.",
		"Heat a non-stick skillet or griddle over medium heat. Pour 1/4 cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface of the pancake and the bottom is golden brown, about 2-3 minutes.",
		"Flip the pancake and cook until the other side is golden brown, about 1-2 minutes more.",
		"Repeat with the remaining batter, adjusting the heat as necessary to prevent burning.",
		"Serve the bacon pancakes warm with maple syrup. Enjoy!"]},
		
		{"id":2,"name":"Go Vegetarian","img":"./photos/Vegetarian.jpg","sweet":false,
		 "ingredients":["1 cup all-purpose flour", "1 1/2 cups of non-dairy milk", "3 large eggs or egg substitute (such as flax eggs)", "1 tablespoon sugar" ,"1/2 teaspoon salt" ,"2 tablespoons vegetable oil or melted butter"],
		 "instructions":["In a mixing bowl, whisk together the flour, sugar, and salt.",
		 "In another bowl, whisk together the eggs (or egg substitute), milk (or non-dairy milk), and oil until combined.",
		 "Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.",
		 "Heat a non-stick skillet over medium-high heat and add a small amount of oil or butter.",
		 "Pour 1/2 cup of batter into the skillet, tilting the pan to spread the batter evenly.",
		 "Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		 "Repeat the process with the remaining batter, adding more oil or butter to the pan as needed.", 
		 "Serve the pancake hot, topped with your favorite toppings such as fresh fruit, nuts, honey, or maple syrup."]},
		
		{"id":3,"name":"Go Mediterranean","img":"./photos/dsc0474_2.jpeg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1 tablespoon chopped fresh herbs (such as parsley, basil, or oregano)", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons olive oil", "1/2 cup crumbled feta cheese", "1/4 cup chopped sun-dried tomatoes", "1/4 cup chopped kalamata olives", "Additional olive oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, herbs, salt, and black pepper.", 
		"In another bowl, whisk together the eggs and milk until combined.", 
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.", 
		"Stir in the olive oil, feta cheese, sun-dried tomatoes, and kalamata olives.", 
		"Heat a non-stick skillet over medium-high heat and add a small amount of olive oil.", "Pour 1/2 cup of batter into the skillet, tilting the pan to spread the batter evenly.", 
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.", "Repeat the process with the remaining batter, adding more olive oil to the pan as needed.", 
		"Serve the pancake hot, topped with additional feta cheese and herbs if desired."]},
		
		{"id":4,"name":"Go Tennessee","img":"./photos/images.jpg","sweet":false, 
		"ingredients":["1 1/2 cups all-purpose flour", "3 1/2 teaspoons baking powder", "1 teaspoon salt", "1 tablespoon sugar", "1 1/4 cups milk", "1 large egg", "3 tablespoons unsalted butter, melted", "Additional butter or oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, baking powder, salt, and sugar.",
		"In another bowl, whisk together the milk, egg, and melted butter until combined.",
		"Gradually add the milk mixture to the flour mixture, whisking until smooth and well combined.", 
		"Heat a non-stick skillet over medium-high heat and melt a small amount of butter or oil.", 
		"Pour 1/4 cup of batter into the skillet, tilting the pan to spread the batter evenly.", 
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Repeat the process with the remaining batter, adding more butter or oil to the pan as needed.",
		"Serve the Tennessee-style pancakes hot, topped with a pat of butter and warm maple syrup."]},
		
		{"id":5,"name":"Go Meaty","img":"./photos/Meaty.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons olive oil", "1/2 pound ground beef", "1/2 cup sliced pepperoni", "1/2 cup sliced salami", "1/2 cup sliced mixed peppers", "1/2 cup sliced onions", "1 cup shredded mozzarella cheese", "Additional olive oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, salt, and black pepper.",
		"In another bowl, whisk together the eggs and milk until combined.",
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.",
		"Heat a non-stick skillet over medium-high heat and add a small amount of olive oil.",
		"Add the ground beef to the skillet and cook, stirring occasionally, until browned and cooked through.",
		"Add the sliced pepperoni, salami, mixed peppers, and onions to the skillet and sauté for 3-4 minutes or until the vegetables are tender.",
		"Pour the pancake batter over the beef and vegetable mixture in the skillet, tilting the pan to spread the batter evenly.",
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Sprinkle the shredded mozzarella cheese over the pancake and cover the skillet with a lid or foil.",
		"Cook for an additional 1-2 minutes or until the cheese is melted.",
		"Serve the pancake hot, sliced into wedges."]},
		
		{"id":6,"name":"Go Elgant","img":"./photos/elagant.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons butter", "2 cups fresh spinach", "1 cup wild mushrooms", "1/2 pound poached salmon, flaked", "1/4 cup white wine", "1/4 cup heavy cream", "2 tablespoons unsalted butter", "Salt and black pepper to taste"],
		"instructions":["In a mixing bowl, whisk together the flour, salt, and black pepper.", 
		"In another bowl, whisk together the eggs and milk until combined.",
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.", 
		"Heat a non-stick skillet over medium-high heat and add a small amount of butter.",
		"Add the spinach and wild mushrooms to the skillet and sauté for 3-4 minutes or until the vegetables are tender.",
		"Add the poached salmon and stir to combine with the vegetables.",
		"Pour the pancake batter over the salmon and vegetable mixture in the skillet, tilting the pan to spread the batter evenly.",
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Remove the pancake from the skillet and transfer it to a serving platter.",
		"To make the white wine sauce, add the white wine to the same skillet used to make the pancake, and cook over medium heat until reduced by half.",
		"Add the heavy cream and unsalted butter, and cook for another 1-2 minutes or until the sauce thickens.",
		"Season with salt and black pepper to taste.",
		"Pour the white wine sauce over the pancake, and serve it hot."]},
		
		{"id":7,"name":"Go Italian","img":"./photos/italian.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1/2 cup Bolognese sauce", "1/4 cup grated Parmesan cheese", "1 cup sliced garlic mushrooms", "2 tablespoons olive oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the olive oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"In a separate pan, heat the Bolognese sauce and garlic mushrooms over medium heat until heated through.",
		"To serve, stack the pancakes and top with the Bolognese sauce and garlic mushrooms. Sprinkle with grated Parmesan cheese."]},
		
		{"id":8,"name":"Go Thai","img":"./photos/thai.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup cooked and shredded chicken breast", "1/2 cup diced mixed peppers (red, green, and yellow)", "1/4 cup diced onion", "1/4 cup mild Thai curry sauce", "2 tablespoons vegetable oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.", 
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.", 
		"In a separate pan, sauté the mixed peppers and onion over medium heat until they are softened.", 
		"Add the cooked and shredded chicken breast and mild Thai curry sauce to the pepper and onion mixture. Cook until heated through.",
		"To serve, stack the pancakes and spoon the chicken and vegetable mixture over the top of the pancakes."]},
		
		{"id":9,"name":"Go Mexican","img":"./photos/mex.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup Chili Con Carne", "1/2 cup guacamole", "1/2 cup salsa", "1/4 cup soured cream", "1/2 cup crushed tortilla chips", "2 tablespoons vegetable oil]"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"To assemble, place a pancake on a plate and spread a generous spoonful of Chili Con Carne over the pancake.",
		"Top with a dollop of guacamole, salsa, and soured cream.",
		"Sprinkle crushed tortilla chips over the top of the pancake and serve."]},

		{"id":10,"name":"Go Smokey","img":"./photos/smo.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup pulled pork", "1/4 cup smoky BBQ sauce", "1/2 cup coleslaw", "1/2 cup Dutch apple mousse", "1/2 cup cooked and diced potatoes", "2 tablespoons vegetable oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"In a separate pan, heat the pulled pork and smoky BBQ sauce over medium heat until heated through.",
		"To serve, stack the pancakes and top with the pulled pork and BBQ sauce.",
		"Sprinkle the diced potatoes over the top of the pulled pork.",
		"Add a spoonful of coleslaw and a dollop of Dutch apple mousse to the plate."]},
		
		{"id":11,"name":"Go Caribbean","img":"./photos/car.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1/2 cup cooked, shredded chicken breast", "1/2 cup Caribbean Jerk BBQ sauce", "1 mango, diced", "1 lime, cut into wedges", "Salt and pepper to taste", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"In a separate pan, heat the shredded chicken breast with Caribbean Jerk BBQ sauce over medium heat. Cook for 3-4 minutes or until heated through. Season with salt and pepper to taste.",
		"To assemble, place a pancake on a plate, top with a spoonful of the chicken and BBQ sauce mixture, and sprinkle with diced mango. Repeat with another pancake, chicken and mango until desired stack is reached.",
		"Squeeze fresh lime juice over the top of the pancake stack.",
		"Serve warm and enjoy your Caribbean-inspired pancake creation!"]},
		
		{"id":12,"name":"Go Oriential","img":"./photos/ori.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1/2 cup shredded crispy duck", "2 spring onions, thinly sliced", "1/4 cucumber, thinly sliced", "2 tablespoons hoisin sauce", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"In a separate pan, heat the shredded crispy duck over medium heat until it starts to crisp up.",
		"To assemble, place a pancake on a plate, top with a spoonful of the crispy duck, followed by the sliced cucumber and spring onions.",
		"Drizzle hoisin sauce over the top of the ingredients.",
		"Roll up the pancake and enjoy your savory and delicious Crispy Duck Pancake with Spring Onions, Cucumber, and Hoi Sin Sauce!"]},
		
		{"id":13,"name":"Go Hot with Cherries","img":"./photos/che.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1/2 cup pitted and halved cherries", "2 scoops strawberry ice cream", "Whipped cream", "Chocolate sauce", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"In a separate pan, heat the cherries over medium heat until they start to soften and release their juices.",
		"To assemble, place a pancake on a plate, top with a scoop of strawberry ice cream, followed by a spoonful of the cooked cherries.",
		"Add a dollop of whipped cream on top of the cherries.",
		"Drizzle chocolate sauce over the top of the whipped cream.",
		"Repeat with another pancake, ice cream, cherries, whipped cream, and chocolate sauce until desired stack is reached.",
		"Serve immediately and enjoy your sweet and indulgent Cherry and Strawberry Ice Cream Pancake with Whipped Cream and Chocolate Sauce!"]},
		
		{"id":14,"name":"Go Bananas","img":"./photos/ban.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1 ripe banana, thinly sliced", "2 scoops vanilla ice cream", "Whipped cream", "Hagelslag (Dutch chocolate sprinkles)", "Chocolate sauce", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.", 
		"Heat a non-stick pan over medium heat and add a small amount of oil.", 
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"In a separate pan, heat the sliced banana over medium heat until they start to caramelize.",
		"To assemble, place a pancake on a plate, top with a scoop of vanilla ice cream, followed by a spoonful of the caramelized banana.",
		"Add a dollop of whipped cream on top of the banana.",
		"Sprinkle hagelslag over the top of the whipped cream.",
		"Drizzle chocolate sauce over the top of the hagelslag.",
		"Repeat with another pancake, ice cream, banana, whipped cream, hagelslag, and chocolate sauce until desired stack is reached.",
		"Serve immediately and enjoy your sweet and decadent Banana and Vanilla Ice Cream Pancake with Whipped Cream, Hagelslag, and Chocolate Sauce!"]},
		
		{"id":15,"name":"Go Sultan","img":"./photos/sul.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1 apple, peeled and grated", "1/2 teaspoon ground cinnamon", "1/4 cup sultanas (raisins)", "2 scoops vanilla ice cream", "Whipped cream", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Add the grated apple, ground cinnamon, and sultanas to the pancake batter and mix well.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"To assemble, place a pancake on a plate, top with a scoop of vanilla ice cream.",
		"Add a dollop of whipped cream on top of the ice cream.",
		"Repeat with another pancake, ice cream, and whipped cream until desired stack is reached.",
		"Serve immediately and enjoy your classic and delicious Apple and Cinnamon Pancake with Sultanas, Vanilla Ice Cream, and Whipped Cream!"]},
		
		{"id":16,"name":"Go Berries","img":"./photos/ber.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "Mixed berry compote (can use store-bought or make your own by cooking mixed berries with sugar and water until thickened)", "2 scoops strawberry ice cream", "Whipped crea", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"To assemble, place a pancake on a plate, spoon some mixed berry compote over the top.",
		"Add a scoop of strawberry ice cream on top of the compote.",
		"Add a dollop of whipped cream on top of the ice cream.",
		"Repeat with another pancake, compote, ice cream, and whipped cream until desired stack is reached.",
		"Serve immediately and enjoy your fruity and delicious Mixed Berry and Strawberry Ice Cream Pancake with Whipped Cream!"]},
		

		{"id":17,"name":"Go Dreamy Chocolate","img":"./photos/cho.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1/4 cup chocolate drops", "Chocolate ice cream", "Whipped cream", "Hagelslag (Dutch chocolate sprinkles)", "Chocolate sauce", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Add the chocolate drops to the pancake batter and mix well.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter.",
		"To assemble, place a pancake on a plate, top with a scoop of chocolate ice cream.",
		"Add a dollop of whipped cream on top of the ice cream.",
		"Sprinkle some hagelslag over the whipped cream.",
		"Repeat with another pancake, ice cream, whipped cream, and hagelslag until desired stack is reached.",
		"Drizzle some chocolate sauce over the top of the pancake stack.",
		"Serve immediately and enjoy your rich and decadent Chocolate Drop and Ice Cream Pancake with Whipped Cream, Hagelslag, and Chocolate Sauce!"]},
		
		{"id":18,"name":"Go Toffee Apple","img":"./photos/app.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "1 apple, peeled and thinly sliced", "Vanilla ice cream", "Whipped cream", "Hagelslag (Dutch chocolate sprinkles)", "Sticky toffee sauce", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Add a few apple slices on top of the batter.",
		"Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter and apple slices.",
		"To assemble, place a pancake on a plate, top with a scoop of vanilla ice cream.",
		"Add a dollop of whipped cream on top of the ice cream.",
		"Sprinkle some hagelslag over the whipped cream.",
		"Repeat with another pancake, ice cream, whipped cream, and hagelslag until desired stack is reached.",
		"Drizzle some sticky toffee sauce over the top of the pancake stack.",
		"Serve immediately and enjoy your warm and comforting Apple and Ice Cream Pancake with Whipped Cream, Hagelslag, and Sticky Toffee Sauce!"]},
		
		{"id":19,"name":"Go Strawberries","img":"./photos/str.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "Fresh strawberries, sliced", "Fresh mint leaves, chopped", "Strawberry ice cream", "Whipped cream", "Strawberry puree", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Add a few sliced strawberries and a sprinkle of chopped fresh mint on top of the batter.",
		"Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter, sliced strawberries, and chopped mint.",
		"To assemble, place a pancake on a plate, top with a scoop of strawberry ice cream.",
		"Add a dollop of whipped cream on top of the ice cream.",
		"Drizzle some strawberry puree over the whipped cream.",
		"Repeat with another pancake, ice cream, whipped cream, and strawberry puree until desired stack is reached.",
		"Garnish with additional sliced strawberries and fresh mint leaves.",
		"Serve immediately and enjoy your refreshing Strawberry and Ice Cream Pancake with Whipped Cream, Strawberry Puree, and Fresh Mint!"]},
		
		{"id":20,"name":"Go Raspberries","img":"./photos/ras.jpg","sweet":true, 
		"ingredients":["1 cup pancake mix", "1/2 cup water", "Fresh raspberries", "White chocolate drops", "White chocolate mousse", "Raspberry puree", "Oil for cooking"],
		"instructions":["In a bowl, mix the pancake mix and water until smooth.",
		"Heat a non-stick pan over medium heat and add a small amount of oil.",
		"Pour 1/4 cup of the pancake batter onto the pan and spread it evenly. Add a few white chocolate drops and a few fresh raspberries on top of the batter.",
		"Cook until the edges start to dry out and the bottom is golden brown, then flip and cook the other side until golden brown. Repeat with the remaining batter, white chocolate drops, and fresh raspberries.",
		"To assemble, place a pancake on a plate, top with a spoonful of white chocolate mousse.",
		"Add a few fresh raspberries on top of the mousse.",
		"Drizzle some raspberry puree over the raspberries.",
		"Repeat with another pancake, white chocolate mousse, fresh raspberries, and raspberry puree until desired stack is reached.",
		"Garnish with additional white chocolate drops and fresh raspberries.",
		"Serve immediately and enjoy your decadent Raspberry and White Chocolate Pancake with White Chocolate Mousse and Raspberry Puree!",]}]

	
}