let data = {
	"pancakes":[{"id":1,"name":"Go Bacon","img":"./photos/bacon-pancakes-resize-6.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1 tablespoon sugar", "1/2 teaspoon salt", "2 tablespoons unsalted butter, melted", "Additional butter or oil for cooking"],
		"instructions":["Cook the bacon in a skillet over medium heat until crispy. Transfer to a paper towel-lined plate and crumble into small pieces.",
		"In a large bowl, whisk together the flour, sugar, baking powder, and salt.",
		"In a separate bowl, whisk the egg, milk, and melted butter.",
		"Add the wet ingredients to the dry ingredients and whisk until just combined. Stir in the crumbled bacon.",
		"Heat a non-stick skillet or griddle over medium heat. Pour 1/4 cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface of the pancake and the bottom is golden brown, about 2-3 minutes.",
		"Flip the pancake and cook until the other side is golden brown, about 1-2 minutes more.",
		"Repeat with the remaining batter, adjusting the heat as necessary to prevent burning.",
		"Serve the bacon pancakes warm with maple syrup. Enjoy!"]},
		
		{"id":2,"name":"Go Vegetarian","img":"./photos/Vegetarian.jpg","sweet":false,
		 "ingredients":["1 cup all-purpose flour", "1 1/2 cups of non-dairy milk", "3 large eggs or egg substitute (such as flax eggs)", "1 tablespoon sugar" ,"1/2 teaspoon salt" ,"2 tablespoons vegetable oil or melted butter"],
		 "instructions":["In a mixing bowl, whisk together the flour, sugar, and salt.",
		 "In another bowl, whisk together the eggs (or egg substitute), milk (or non-dairy milk), and oil until combined.",
		 "Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.",
		 "Heat a non-stick skillet over medium-high heat and add a small amount of oil or butter.",
		 "Pour 1/2 cup of batter into the skillet, tilting the pan to spread the batter evenly.",
		 "Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		 "Repeat the process with the remaining batter, adding more oil or butter to the pan as needed.", 
		 "Serve the pancake hot, topped with your favorite toppings such as fresh fruit, nuts, honey, or maple syrup."]},
		
		{"id":3,"name":"Go Mediterranean","img":"./photos/dsc0474_2.jpeg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1 tablespoon chopped fresh herbs (such as parsley, basil, or oregano)", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons olive oil", "1/2 cup crumbled feta cheese", "1/4 cup chopped sun-dried tomatoes", "1/4 cup chopped kalamata olives", "Additional olive oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, herbs, salt, and black pepper.", 
		"In another bowl, whisk together the eggs and milk until combined.", 
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.", 
		"Stir in the olive oil, feta cheese, sun-dried tomatoes, and kalamata olives.", 
		"Heat a non-stick skillet over medium-high heat and add a small amount of olive oil.", "Pour 1/2 cup of batter into the skillet, tilting the pan to spread the batter evenly.", 
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.", "Repeat the process with the remaining batter, adding more olive oil to the pan as needed.", 
		"Serve the pancake hot, topped with additional feta cheese and herbs if desired."]},
		
		{"id":4,"name":"Go Tennessee","img":"./photos/images.jpg","sweet":false, 
		"ingredients":["1 1/2 cups all-purpose flour", "3 1/2 teaspoons baking powder", "1 teaspoon salt", "1 tablespoon sugar", "1 1/4 cups milk", "1 large egg", "3 tablespoons unsalted butter, melted", "Additional butter or oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, baking powder, salt, and sugar.",
		"In another bowl, whisk together the milk, egg, and melted butter until combined.",
		"Gradually add the milk mixture to the flour mixture, whisking until smooth and well combined.", 
		"Heat a non-stick skillet over medium-high heat and melt a small amount of butter or oil.", 
		"Pour 1/4 cup of batter into the skillet, tilting the pan to spread the batter evenly.", 
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Repeat the process with the remaining batter, adding more butter or oil to the pan as needed.",
		"Serve the Tennessee-style pancakes hot, topped with a pat of butter and warm maple syrup."]},
		
		{"id":5,"name":"Go Meaty","img":"./photos/Meaty.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons olive oil", "1/2 pound ground beef", "1/2 cup sliced pepperoni", "1/2 cup sliced salami", "1/2 cup sliced mixed peppers", "1/2 cup sliced onions", "1 cup shredded mozzarella cheese", "Additional olive oil for cooking"],
		"instructions":["In a mixing bowl, whisk together the flour, salt, and black pepper.",
		"In another bowl, whisk together the eggs and milk until combined.",
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.",
		"Heat a non-stick skillet over medium-high heat and add a small amount of olive oil.",
		"Add the ground beef to the skillet and cook, stirring occasionally, until browned and cooked through.",
		"Add the sliced pepperoni, salami, mixed peppers, and onions to the skillet and sauté for 3-4 minutes or until the vegetables are tender.",
		"Pour the pancake batter over the beef and vegetable mixture in the skillet, tilting the pan to spread the batter evenly.",
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Sprinkle the shredded mozzarella cheese over the pancake and cover the skillet with a lid or foil.",
		"Cook for an additional 1-2 minutes or until the cheese is melted.",
		"Serve the pancake hot, sliced into wedges."]},
		
		{"id":6,"name":"Go Elgant","img":"./photos/elagant.jpg","sweet":false, 
		"ingredients":["1 cup all-purpose flour", "1 1/2 cups milk", "3 large eggs", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "2 tablespoons butter", "2 cups fresh spinach", "1 cup wild mushrooms", "1/2 pound poached salmon, flaked", "1/4 cup white wine", "1/4 cup heavy cream", "2 tablespoons unsalted butter", "Salt and black pepper to taste"],
		"instructions":["In a mixing bowl, whisk together the flour, salt, and black pepper.", 
		"In another bowl, whisk together the eggs and milk until combined.",
		"Gradually add the egg mixture to the flour mixture, whisking until smooth and well combined.", 
		"Heat a non-stick skillet over medium-high heat and add a small amount of butter.",
		"Add the spinach and wild mushrooms to the skillet and sauté for 3-4 minutes or until the vegetables are tender.",
		"Add the poached salmon and stir to combine with the vegetables.",
		"Pour the pancake batter over the salmon and vegetable mixture in the skillet, tilting the pan to spread the batter evenly.",
		"Cook for about 2-3 minutes on each side or until the pancake is golden brown.",
		"Remove the pancake from the skillet and transfer it to a serving platter.",
		"To make the white wine sauce, add the white wine to the same skillet used to make the pancake, and cook over medium heat until reduced by half.",
		"Add the heavy cream and unsalted butter, and cook for another 1-2 minutes or until the sauce thickens.",
		"Season with salt and black pepper to taste.",
		"Pour the white wine sauce over the pancake, and serve it hot."]},
		
		{"id":7,"name":"Go Italian","img":"./photos/italian.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1/2 cup Bolognese sauce", "1/4 cup grated Parmesan cheese", "1 cup sliced garlic mushrooms", "2 tablespoons olive oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the olive oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"In a separate pan, heat the Bolognese sauce and garlic mushrooms over medium heat until heated through.",
		"To serve, stack the pancakes and top with the Bolognese sauce and garlic mushrooms. Sprinkle with grated Parmesan cheese."]},
		
		{"id":8,"name":"Go Thai","img":"./photos/thai.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup cooked and shredded chicken breast", "1/2 cup diced mixed peppers (red, green, and yellow)", "1/4 cup diced onion", "1/4 cup mild Thai curry sauce", "2 tablespoons vegetable oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.", 
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.", 
		"In a separate pan, sauté the mixed peppers and onion over medium heat until they are softened.", 
		"Add the cooked and shredded chicken breast and mild Thai curry sauce to the pepper and onion mixture. Cook until heated through.",
		"To serve, stack the pancakes and spoon the chicken and vegetable mixture over the top of the pancakes."]},
		
		{"id":9,"name":"Go Mexican","img":"./photos/mex.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup Chili Con Carne", "1/2 cup guacamole", "1/2 cup salsa", "1/4 cup soured cream", "1/2 cup crushed tortilla chips", "2 tablespoons vegetable oil]"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"To assemble, place a pancake on a plate and spread a generous spoonful of Chili Con Carne over the pancake.",
		"Top with a dollop of guacamole, salsa, and soured cream.",
		"Sprinkle crushed tortilla chips over the top of the pancake and serve."]},

		{"id":10,"name":"Go Smokey","img":"./photos/smo.jpg","sweet":false, 
		"ingredients":["1 cup pancake mix", "1/2 cup milk", "1 egg", "1 cup pulled pork", "1/4 cup smoky BBQ sauce", "1/2 cup coleslaw", "1/2 cup Dutch apple mousse", "1/2 cup cooked and diced potatoes", "2 tablespoons vegetable oil"],
		"instructions":["In a mixing bowl, combine the pancake mix, milk, and egg. Whisk together until the batter is smooth.",
		"Heat a nonstick pan over medium heat. Add the vegetable oil and swirl to coat the pan.",
		"Pour 1/4 cup of the pancake batter onto the pan for each pancake. Cook until bubbles appear on the surface and the edges start to set.",
		"Flip the pancake and cook for an additional 1-2 minutes until cooked through.",
		"Repeat with the remaining batter until all the pancakes are cooked.",
		"In a separate pan, heat the pulled pork and smoky BBQ sauce over medium heat until heated through.",
		"To serve, stack the pancakes and top with the pulled pork and BBQ sauce.",
		"Sprinkle the diced potatoes over the top of the pulled pork.",
		"Add a spoonful of coleslaw and a dollop of Dutch apple mousse to the plate."]},
		
		{"id":11,"name":"Go Caribbean","img":"./PancakeBackGround.jpg","sweet":false, 
		"ingredients":["Chicken Breast", "Caribbean Jerk BBQ Sauce", "Mango", "Lime"]},
		
		{"id":12,"name":"Go Oriential","img":"./PancakeBackGround.jpg","sweet":false, 
		"ingredients":["Crispy Duck", "Spring Onions", "Cucumber", "Hoi Sin Sauce"]},
		
		{"id":13,"name":"Go Hot with Cherries","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Cherries", "Strawberry Ice Cream", "Whipped Cream", "Chocolate Sauce"]},
		
		{"id":14,"name":"Go Bananas","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Bananas", "Vanilla Ice Cream", "Whipped Cream", "Hagelslag", "chocolate sauce"]},
		
		{"id":15,"name":"Go Sultan","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Apple", "Cinnamon", "Sultanas", "Vanilla Ice Cream", "Whipped Cream"]},
		
		{"id":16,"name":"Go Berries","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Mixed Berry composite", "Strawberry Ice Cream", "Whipped Cream"]},
		

		{"id":17,"name":"Go Dreamy Chocolate","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Chocolate Drops", "Chocolate Ice Cream", "Whipped Cream", "Hagelslag", "Chocolate Sauce"]},
		
		{"id":18,"name":"Go Toffee Apple","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Apple Slices", "Vanilla Ice Cream", "Whipped Cream", "Hagelslag", "Sticky Toffee Sauce"]},
		
		{"id":19,"name":"Go Strawberries","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Fresh Strawberries", "Fresh Mint", "Strawberry Ice Cream", "Whipped Cream", "Strawberry Puree"]},
		
		{"id":20,"name":"Go Raspberries","img":"./PancakeBackGround.jpg","sweet":true, 
		"ingredients":["Fresh Raspberries", "White Chocolate Drops", "White Chocolate Mousse", "Raspberry Puree"]}]

	
}